models/enums/dissertation_role_status.py
models/enums/dissertation_status.py
models/enums/status_types.py
tests/views/test_information.py
urls.py
views/information.py

OSIS-2166 increase test coverage

---

tests/models/test_dissertation.py

OD-57 correction du bug de test_count_by_proposition

---

forms.py
models/adviser.py
models/dissertation.py
models/dissertation_role.py
models/faculty_adviser.py
models/proposition_dissertation.py
perms.py
templates/manager_dissertations_edit.html
tests/models/test_adviser.py
tests/test_perms.py
tests/views/test_dissertation.py
tests/views/test_information.py
views/dissertation.py

Od 39 refactoring perms pour education group

---

forms.py

OD-39 Ajout distinct dans ManagerDissertationForm

---

tests/views/test_dissertation.py

Test_dissertation random test fail correction

---

models/offer_proposition.py

Référence Jira : Fix_recent_accronym ( pas de ticket)

Fix_recent_accronym

---

locale/en/LC_MESSAGES/django.po
locale/fr_BE/LC_MESSAGES/django.po
templates/dissertationdocumentfile_confirm_delete_inner.html
templates/dissertations_detail.html
templates/manager_dissertations_detail.html
tests/factories/dissertation_document_file.py
tests/views/test_dissertation_document_file.py
urls.py
views/upload_dissertation_file.py

Od 79 gestion des fichier côté dissertation.

---

migrations/0047_check_if_propositions_dissertations_attached_to_offer_propossition_with_education_group__not_none.py
migrations/utils/__init__.py
migrations/utils/clean_db_with_no_educ_group.py
tests/migrations/__init__.py
tests/migrations/test_clean_db_with_no_educ_group.py

Od 61 migration create subjet if education_group none

---

migrations/utils/clean_db_with_no_educ_group.py

OD-61 add logging with logger

---

templates/dissertations.html

OD-83 remplacement de deux font awesome

---

migrations/utils/clean_db_with_no_educ_group.py

Référence Jira : OD-61
Concerne OD-61 (migration 0047 de dissertation: actuellement en dev et test) , cette correction empêche la création de doublon dans la table proposition_offer

OD-61 correction petit bug suite aux tests

---

locale/en/LC_MESSAGES/django.po
locale/fr_BE/LC_MESSAGES/django.po
views/upload_dissertation_file.py

Od 82 add dissertation_update when add file

---

templates/dissertations.html

OD-85 ajout font awesome coté adviser

---

models/dissertation.py
models/dissertation_document_file.py
models/dissertation_group.py
models/dissertation_role.py
models/dissertation_update.py
models/faculty_adviser.py
models/offer_proposition.py
models/proposition_dissertation.py
models/proposition_document_file.py
models/proposition_offer.py
models/proposition_role.py

Prepare OSIS to Django2.0

---

views/information.py
views/proposition_dissertation.py

[Django2.0] Fix tests

---

locale/en/LC_MESSAGES/django.po
locale/fr_BE/LC_MESSAGES/django.po
models/dissertation.py
templates/manager_dissertations_detail.html
templates/manager_dissertations_list.html
tests/views/test_dissertation.py

 OD-89 Allow to go back to To Receive status when dissertation delayed

---

models/dissertation.py
views/dissertation.py
views/proposition_dissertation.py

[OSIS-3369] Use correct academic year as current one

---

.travis.yml
forms.py
models/dissertation.py
models/faculty_adviser.py
models/proposition_dissertation.py
tests/forms/test_dissertation.py
tests/models/test_dissertation.py
tests/models/test_faculty_adviser.py

Hotfix OD-91 (don't exclude propositions for manager) and OD-94 (fix admin display bug)

---

.travis.yml

Test only dissertation !? - Remove useless travis logs

---

views/information.py

Deprecated render

---

views/proposition_dissertation.py

OD-108 Correction apres passage en Django 2

---

templates/manager_dissertations_list.html
templates/manager_proposition_dissertations_list.html

OD-113 Faire disparaitre le spinner lorsque l'on génère un export excel

---

fixtures/message_template.json

OD-114 Modification de la fixture de template d'email

---

views/information.py

Adapt changes from Osis

---

migrations/0050_auto_20191209_1018.py
utils/request.py

OD-117 Remove méthode inutilisé

---

views/information.py

Adapt person model from osis

---

templates/dissertation/adviser_list.html
templates/dissertation/offerproposition_filter.html

Add removed templates (Sorry)

---

templates/dissertation/offerproposition_filter.html

Remove load check

---

forms.py
locale/en/LC_MESSAGES/django.po
locale/fr_BE/LC_MESSAGES/django.po
templates/manager_information_add_person.html
views/information.py

OD-118 Ajout d'un clean email pour éviter l'ecran d'erreur

---

locale/en/LC_MESSAGES/django.po
locale/fr_BE/LC_MESSAGES/django.po
templates/dissertation/offerproposition_filter.html
templates/informations.html
templates/manager_informations_detail.html
views/faculty_adviser/search.py

Hotfix/OD-119 Correction de traductions et d'entête de tableaux

---

views/proposition_dissertation.py

- Ne prendre que les sujets de mémoire actif
Référence Jira : OD-120

OD-120 Les Sujets de mémoires désactivés restent visible pour les gestionnaires

---

models/adviser.py
models/dissertation.py
models/offer_proposition.py

Use get_object_or_none from osis_common

---

locale/fr_BE/LC_MESSAGES/django.po

translations

---

tests/models/test_dissertation.py

FIxed test

---

locale/fr_BE/LC_MESSAGES/django.po

OD-123 Fix translation for Dissertation Manager

---

models/offer_proposition.py

Passage par GroupYear pour récupérer le main_teaching_campus

---

models/offer_proposition.py

OD-126 Quick fix : hide non important data causing error with .get()

---

tests/models/test_offer_proposition.py

OSIS-5571 removed unused OfferYearFactory usage

---

views/dissertation.py

OSIS-5378 Modify import after refactoring of Tutor role

---

perms.py

[QA]Removed private Python 2 compatibility APIs : available_attrs

---

perms.py

[TEST]Removed private Python 2 compatibility APIs : available_attrs

---

perms.py

[MASTER]Removed private Python 2 compatibility APIs : available_attrs

---

models/dissertation.py

Enlevement de dissertation file dans l'admin

---

templates/file_upload_dissertaton_modal.html
templates/manager_dissertations_detail.html

FIxed probleme d'upload management

---

api/views/dissertation.py

Fixed problème quand upload côté portail

---

api/serializers/dissertation.py
api/views/dissertation.py

Ajout des serializer_field_mapping

---

locale/fr_BE/LC_MESSAGES/django.po

Fixed translate

---

models/proposition_dissertation.py

Corrigé l'accès et modification proposition_dissertation via l'admin

---

fixtures/message_template.json
utils/emails_dissert.py

OSIS-7518 Ajout d'infos dans le template des commissions

---

schema.yml

[MASTER] OSIS-7894 defend_year nullable True dans le schéma

---

schema.yml

[QA] OSIS-7894 defend_year nullable True dans le schéma

---

schema.yml

[DEV] OSIS-7894 defend_year nullable True dans le schéma

---

views/faculty_adviser/delete.py
views/upload_dissertation_file.py
views/upload_proposition_file.py

[WIP] Python migration

---

models/adviser.py
models/proposition_dissertation.py

[QA] Change str adviser
